server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/laboratory_management
    username: root
    password: QQ1438255191qq++

mybatis:
  mapper-locations: classpath:com/mapper/*.xml
  type-aliases-package: com.lyun.laboratorymanagement.entity